### ISSUE TITLE
Kdeconnect not work

### ISSUE THREAD

**Issue by bvbfan** [KaOSx/apps#19] opened 2015-02-23 20:11 UTC
[toni@toni-sony ~]$ kdeconnect-cli -v
kdeconnect-cli 0.8
[toni@toni-sony ~]$ kdeconnect-cli -l
ALCATEL ONE TOUCH 6010X: 6cbae2f6dfbfe17c (reachable)
1 devices found
[toni@toni-sony ~]$ kdeconnect-cli --pair -d 6cbae2f6dfbfe17c
Question mark present on phone (v0.8), but cannot confirm, cause not present yes/no buttons.
[toni@toni-sony ~]$ kdeconnect-cli --unpair -d 6cbae2f6dfbfe17c
Already not paired
Request from phone to PC, notification is shown, but when click "yes" print 'cancelled by user'

**Comment by demmm** [comment] 2015-02-23 21:04
Can't reproduce.
Quite a few devices tested here to pair.
$ kdeconnect-cli -v
kdeconnect-cli 0.8

$ kdeconnect-cli -l
- Samsung Galaxy Nexus: 17ba2023535364c5 (paired and reachable)
- Nexus 7: 561d273071cd1f7c (reachable)
2 devices found

**Comment by bvbfan** [comment] 2015-02-24 19:11
You're right. I reinstall the android app and now can be paired. I test with Galaxy Nexus, Alcatel Star when request from PC both connected, but when request from phone both can't - 'cancelled by user'. Topic may be closed.

**Comment by demmm** [comment] 2015-02-24 19:13
Closing, seems an android app issue, not KDE.
Please re-open if you find otherwise.

**Closed by demmm** 2015-02-24 19:13 UTC
