### ISSUE TITLE
Qupzilla se cierra repentinamente (QupZilla suddenly closes)

### ISSUE THREAD

**Issue by duvansuarez** [KaOSx/apps#51] opened 2016-04-05 19:20 UTC
Aveces que uso este navegador en su nueva version, este se cierra repentinamente, es posible que sea Qtwebengine.

Sometimes I use this browser in its new version, this closes suddenly, it may be Qtwebengine.

**Comment by demmm** [comment] 2016-04-05 21:49
Please make a proper report.
What is the backtrace when you run Qupzilla from cli?
What version are you reporting about?  Is your system fully updated?  What repos in use?  What sites causing this?  What graphics driver in use and so on.
"its" and "it" are no way to report any.

**Comment by duvansuarez** [comment] 2016-04-08 19:21
en cuanto a la traza inversa no me da ninguna solamente se cierra pero no dice el por que, la version de qupzilla es 2.0.0 , version de QT 5.6, paginas en las que se tiende a cerrar principalmente facebook y youtube.

**Comment by demmm** [comment] 2016-04-08 19:58
Last try to get a real report, answer all questions from my first reply and create proper logs, following:
http://kaosx.us/asking-and-reporting-the-smart-way/

**Comment by demmm** [comment] 2016-04-13 22:03
Not getting any info for a real report, duplicate of https://github.com/KaOSx/apps/issues/52
Continuing with that report.
Closing.
If you want to participate in this issue, comment on the report linked above.

**Closed by demmm** 2016-04-13 22:03 UTC
Labels: waiting for feedback
