### ISSUE TITLE
smb4k Fails to Retreive List of Hosts

### ISSUE THREAD

**Issue by madirishman** [KaOSx/apps#108] opened 2017-03-29 23:39 UTC
#### Submission type

  - [1 ] Bug report
  - [ ] Feature Request

#### Package name & version you are having issues with or have a request for

> smb4k 2.0.0-1
[smb.txt](https://github.com/KaOSx/apps/files/880648/smb.txt) (/etc/smb.conf)

#### Used repositories

> …

#### Expected behaviour

> List of hosts belonging to Domain ( there are three active hosts )

#### Actual behaviour

> Retreiving list of hosts belonging to domain failed. Failed to init messaging context.

#### Steps to reproduce the problem

> Open smb4k, click on DOMAIN Name
#### System info link created by Octopi > Tools > SysInfo

>  https://gist.github.com/anonymous/ba329f3445518a9865ee627f0bb51882

**Comment by demmm** [comment] 2017-03-29 23:52
When did this start?  Update of samba to 4.6.1? Since you use the build repo (and should disable kde-next, not in use), please check if the issue is resolved by using samba from main:
```
sudo pacman -S main/samba
```

**Comment by madirishman** [comment] 2017-03-30 12:40
I'm not sure when it started. I haven't used smb4k in a bit. Yesterday was when I first noticed it. I reverted to the samba in main and same thing. How do I remove 4.6.1? If I try to uninstall it doesn't just remove samba.

**Comment by madirishman** [comment] 2017-03-30 12:43
I'm really okay without smb4k. I added my shares to Places in Dolphin, which I didn't know I could do before. It saves browsing steps.

**Comment by demmm** [comment] 2017-03-30 16:18
Once you install Samba from main it replaces 4.6.1 (from build), you don't remove it.
smb4k should work, that is why it is in the repo, even if dolphin does the job for you.  I need to figure if this is an issue that smb4k is not compatible yet with the Samba 4.6 series (it was build on Samba 4.6.0)
I uploaded the last Samba 4.5 package for you test, again install with pacman -U and it will automatically downgrade and remove any 4.6:
```
sudo pacman -U https://sourceforge.net/projects/kaosx/files/packages/samba-4.5.5-2-x86_64.pkg.tar.xz
```

**Comment by madirishman** [comment] 2017-03-30 16:49
I shut two of my three platforms down and tested on the third which is running SAMBA 4.6.1. It is working. I have seen this before. The NETWORK gets out of sync somehow and I have to reboot all platforms in a particular sequence, which one of these days I'll get around to writing down so I don't forget the sequence. I think it has to do with more than one Master Browser, but I have yet to figure out why. I don't think you have an issue. I think this is a long standing thing that has been there for years and across multiple distros. I may even have read about this in the SAMBA documentation somewhere. I am going to,bring up the other two platforms now and see what hapens. I think the sequence is to bring up the platform that I want as the Master Browser first (My Desktop PC) and then the other two (laptops) in any sequence. I'll let you know what happens. REPO order: build, core, main, and apps; correct? On this laptop where smb4k works I only have core, main, and apps. Should I leave build out?

**Comment by demmm** [comment] 2017-03-30 16:54
Yes, repo order as correct, but best to only have kde-next enabled when it is announced in the forum as being active.
The build repo will see breakage, that is why it is there, to catch it before it moves to all users.  It is up to you if you want to help catch any errors before packages move, or if maximum stability is your goal.

**Comment by madirishman** [comment] 2017-03-30 18:55
After messing around with what I thought was the issue (thick-heade3d you know :))) ) with no luck. I did what you asked pacman -U https://sourceforge.net/projects/kaosx/files/packages/samba-4.5.5-2-x86_64.pkg.tar.xz And yea smb4k is not compatible with the 4.6 series.

**Comment by demmm** [comment] 2017-03-30 19:49
Then this probably needs to be taken upstream at smb4k.  Not much I can do to make it compatible with new Samba.

**Comment by madirishman** [comment] 2017-03-30 20:41
Agreed. I'm ignoring samba in pacman.conf for the time being and using 
the sourceforge version.

**Comment by demmm** [comment] 2017-03-30 20:48
It might actually be an issue in Samba, see this patch used in Fedora:
https://src.fedoraproject.org/cgit/rpms/samba.git/commit/?id=563829e681b9845325e7223c13c2e7b517f7e0df

**Comment by madirishman** [comment] 2017-03-31 01:22
I downloaded it and extracted it to my Build folder. I will reinstall 
SAMBA 4.6.0.1 in the morning. How do I install the patch?

**Comment by demmm** [comment] 2017-03-31 01:25
There is no reference that this fixes smb4k.
You state too, Dolphin works fine with Samba 4.6.1, otherwise I would have already applied the patch.
I will check upstream both smb4k & samba for bug reports regarding this.  Will leave report open in the meantime.

**Comment by madirishman** [comment] 2017-03-31 01:29
Yeah, I'm happy either way. 4.5 is working fine, and I may decide to go 
bnack to 4.6 because I kind of like using Dolphin places over smb4k.

How's your immigration status going? Are you going to be able to stay 
here in the US and keep your farm?

Tom

**Comment by demmm** [comment] 2017-03-31 15:47
Please report back if samba 4.6.2 fixes any, just uploaded to the build repo.

**Comment by madirishman** [comment] 2017-03-31 16:07
No. Same. I had already tried it last night. I downloaded it from 
samba.org, but I retried with the build version just to double check.

**Comment by demmm** [comment] 2018-02-03 08:03
Please report back if this still is an issue.

**Comment by madirishman** [comment] 2018-02-03 12:30
No longer an issue. I closed it

**Closed** 2018-02-03 12:29 UTC
Labels: upstream
