### ISSUE TITLE
Unable to open Octopi

### ISSUE THREAD

**Issue by Nithin-Reddy** [KaOSx/apps#67] opened 2016-07-09 17:23 UTC
#### Submission type

  - [ #] Bug report

#### Version of Application
> ...Octopi - 0.9.0 (dev) (Qt 5.7.0)

#### OS Version
>... KaOS 2016.06

#### Expected behaviour

> … Launch Octopi

#### Actual behaviour

> … Unable to Open

#### Steps to reproduce the problem

> … 1. Search for octopi in Dash and select 'Octopi Notifier' application
    ... 2.under System option from dash select 'Octopi Notifier' application to launch

#### System info link created by Octopi > Tools > SysInfo

> … https://gist.github.com/anonymous/12c09c90a2f1583948cdb26ecca627a5

#### Work-Around 

>... Type Octopi in Console

**Comment by demmm** [comment] 2016-07-09 17:33
octopi-notifier is not the Octopi application, is a systray icon that notifies you of available updates, you can right click this icon and start Octopi from there.
From the menu, select "Add/Remove Software".  That will launch the application called Octopi.

Not a bug, closing.

**Closed by demmm** 2016-07-09 17:33 UTC
