### ISSUE TITLE
can not start docker systemd daemon

### ISSUE THREAD

**Issue by boonkerz** [KaOSx/apps#54] opened 2016-04-17 22:51 UTC
> Apr 18 00:45:36 thomas-pc systemd[1]: Starting Docker Application Container Engine...
Apr 18 00:45:36 thomas-pc docker[1279]: time="2016-04-18T00:45:36.926190116+02:00" level=fatal msg="Failed to connect to containerd. Please make sure containerd is installed in your PATH or
Apr 18 00:45:36 thomas-pc systemd[1]: docker.service: Main process exited, code=exited, status=1/FAILURE

**Comment by demmm** [comment] 2016-04-17 22:54
Please make a proper bug report.
What version are you reporting?  New issue, worked correct previously?  System fully updated?  What repos in use?
To get started with a proper log, Octopi > Tools > SysInfo and paste the returned link here.

**Comment by boonkerz** [comment] 2016-04-17 22:59
fresh install all updated.

https://gist.github.com/anonymous/08ddfc29bd83a4e57e1a70c072c21e80

i think docker have is based on containerd with the last release of it

https://blog.docker.com/2016/04/docker-engine-1-11-runc/

and containerd does not come with the kaos docker app install

**Comment by demmm** [comment] 2016-04-17 23:14
Just to make sure, please show the output of ```pacman-Qi zsh```
Extra needed packages will be added asap.

But looking at your log, seems you are on the wrong distro.  KaOS is NOT Arch based, is NOT compatible with yaourt.
If you are looking for Arch linux or one of its derivatives, please install those.
See https://kaosx.us/faq/#KaOS_is_NOT_another_Arch_based_distribution_right

**Comment by boonkerz** [comment] 2016-04-17 23:19
i'm not looking for an arch based linux i love the look and feel of kaosx :)
and currently only docker fails.

or why do you think this?

**Comment by demmm** [comment] 2016-04-17 23:21
Your log shows all kinds of Arch only commands :)

But docker will be fixed asap, thanks for checking this new package

**Comment by demmm** [comment] 2016-04-18 00:25
New depends are up.
It is save to install them from the [build] repo:
```
sudo pacman -U http://kaosx.tk/repo/build/runc-0.1.0-1-x86_64.pkg.tar.xz http://kaosx.tk/repo/build/containerd-0.2.0-1-x86_64.pkg.tar.xz http://kaosx.tk/repo/build/docker-1.11.0-2-x86_64.pkg.tar.xz
```
A reboot is probably needed to make containerd work

**Comment by demmm** [comment] 2016-05-01 17:39
Is this still an issue?

**Comment by AdamSadovsky** [comment] 2016-05-03 20:30
I think the problem is still there.
https://gist.github.com/anonymous/b0de50c28a195348063dae8adf666775
docker daemon wants docker-containerd, docker-containerd-shim and docker-runc

**Comment by ademirtc** [comment] 2016-05-05 19:22
I solved by creating the following symbolic links:
marks@albus:bin $ ls -la docker*
-rwxr-xr-x docker*
lrwxrwxrwx docker-containerd -> containerd*
lrwxrwxrwx docker-containerd-shim -> containerd-shim*
lrwxrwxrwx docker-runc -> runc*
marks@albus:bin $ pwd
/usr/bin

**Comment by AdamSadovsky** [comment] 2016-05-06 22:29
I can see last update repair docker problem. I can confirm that docker daemon is now starting correctly.

**Comment by demmm** [comment] 2016-05-12 17:17
No further response from initial reporter, assuming it is fixed, closing

**Closed by demmm** 2016-05-12 17:17 UTC
Labels: waiting for feedback
