### ISSUE TITLE
Ktorrent doesn't start properly

### ISSUE THREAD

**Issue by sandef** [KaOSx/apps#37] opened 2015-12-13 17:01 UTC
Ktorrent 4.3.73-1 doesn't start from menu.

Starting from konsole giving:

Failed to open log file /home/aaaaa/.local/share/ktorrent/log: No such 
file or directory

and 

wrong permission for geoip.

Update from new git verions should fix issues.

**Comment by demmm** [comment] 2015-12-13 17:06
Can't reproduce issues here.  Are you fully updated?  Checked if you are using a mirror that is synced?
Did you use the KDE 4 version of ktorrent before?  Tried removing the settings files for ktorrent in your home directory?

**Comment by sandef** [comment] 2015-12-13 17:08
Fresh install Kaos and fresh install ktorrent  4.3.73-1. Yes I tried, did you also?

**Comment by demmm** [comment] 2015-12-13 17:20
Not an answer if you installed correctly
This is a rolling distro, never install any before fully updating.  Use the tools available to you to check if your mirror is synced.  Either by starting octopi, manually by running "mirror-check" or by updating with the .bashrc command "upd"
Make sure to read the basics of using pacman:
http://kaosx.us/pacman-guide/

**Comment by sandef** [comment] 2015-12-13 18:01
System was fully updated when ktorrent was installed.

On an "earlier" system ktorrent, 4.3.73-1 worked, but has config  from the previous git version of ktorrent.

Fresh install ktorrent 4.3.73-1 on fresh fully updated system giving no starting ktorrent.

You understand whether I  must draw it to you?

**Comment by demmm** [comment] 2015-12-13 18:42
OK, issue clear now :)
So if you manually create ~/.local/share/ktorrent issue is fixed?
Looks like this is the issue, ktorrent build will need a patch to correctly set that dir

**Comment by sandef** [comment] 2015-12-13 19:07
Creating manually don't solve all problems. search for log is fixed, but many others files are needed (dht,geoip,groups).

Sadly new version (74) don't solve this either.

From menu ktorrent not starting. From konsole some errors, but ktorrent starts.

**Comment by demmm** [comment] 2015-12-13 19:30
Not starting from menu is a simple fix
```
sed -i 's|Exec=ktorrent %i -caption %c %u|Exec=ktorrent %u|g' ktorrent/org.kde.ktorrent.desktop
```
(or on installed system, edit /usr/share/applications/org.kde.ktorrent.desktop with the above change)
Other issues are fixed after manually creating ~/.local/ktorrent, removing & install ktorrent
So obviously the parts to port the writing to the home directory are not ported yet (or wrongly)

I'll try to make a patch for this

**Comment by sandef** [comment] 2015-12-13 20:07
Nice. Version 75 starts ok. Thank you very much.

**Comment by demmm** [comment] 2015-12-13 20:10
That one is removed again, sorry, didn't think you'd get it this quick.
Fixes to try and make ~/.local/share/ktorrent creation not working yet

**Comment by sandef** [comment] 2015-12-13 20:14
I managed install. :) This fixed menu problem. 

Ktorrent folder manualiy created earlier, I not tested this fix.

**Comment by demmm** [comment] 2015-12-14 02:02
Issue fixed with the above commit & https://github.com/KaOSx/apps/commit/bb7ee49069e41ce228cb1af47d6bad12c341e5c8#diff-154d894ba84b031ab84c0b1646a3dfd4L1

**Closed by demmm** 2015-12-14 02:02 UTC
