### ISSUE TITLE
File not found in Freecad

### ISSUE THREAD

**Issue by toniarta** [KaOSx/apps#44] opened 2016-02-21 19:18 UTC
Hi, When freecad is started and click on Design Part or something, appears an error that say: libTKMesh.so file not found.
But in terminal with locate: /opt/opencascade/lin64/gcc/lib/libTKMesh.so
good work withKaOS project, Regards

**Comment by demmm** [comment] 2016-02-21 19:58
Just to be sure with these packages, did you reboot after the install?  Linking is not working as should really, but often a reboot does fix.

**Comment by toniarta** [comment] 2016-02-21 19:59
Hi, yes I rebooted

**Comment by toniarta** [comment] 2016-02-22 15:22
There is some way to fix it? or I should try to build with sources

**Comment by demmm** [comment] 2016-02-22 16:20
If you know of a fix when you build from sources, why not post it here?
Not known how to fix, since it is not clear what the issue is.

**Comment by toniarta** [comment] 2016-02-22 18:56
Ok, I seem to have found a temporary solution:
Just sudo cp /opt/opencascade/lin64/gcc/lib/* ./opt/freecad/lib/
I'm developer student and I have little knowledge about the correct way to fix it.
For now it works, when I finish the exams I will try to learn how packages are built
Thanks for your time.

**Comment by demmm** [comment] 2016-02-23 04:04
Issue is fixed in the [build] repo.
Please confirm before the packages move to all users.
sudo pacman -U https://kaosx.us/repo/build/vtk-7.0.0-2-x86_64.pkg.tar.xz https://kaosx.us/repo/build/opencascade-1%3A6.9.1-2-x86_64.pkg.tar.xz

**Comment by toniarta** [comment] 2016-02-23 10:38
I have undone my changes, uninstall freecad, installed your modifications and I'v installed freecad again.
Confirmed, Now it's fixed. Thanks

**Closed** 2016-02-24 04:06 UTC
