### ISSUE TITLE
Qtransmission icon is missing in the application menu

### ISSUE THREAD

**Issue by Seeder101** [KaOSx/apps#119] opened 2017-05-15 04:25 UTC
#### Submission type

  - [x] Bug report

#### Package name & version you are having issues with or have a request for

> transmission-qt 2.92-2

#### Used repositories

> apps, main

#### Expected behaviour

> the icon in the appliaction menu is missing 

#### Actual behaviour

> the icon of transmission is missing in the menu -tried installing it serveral time same issue-

#### Steps to reproduce the problem

> dunno actually...

#### System info link created by Octopi > Tools > SysInfo

> https://gist.github.com/0351bb631b4db6710ab9e580f08ba224

Thank you <3

**Comment by demmm** [comment] 2017-05-15 16:05
Cannot reproduce, so this probably is an issue with the icon theme used, and not a packaging issue.
Report back if you can reproduce with the default KaOS "midna" icon theme.

**Comment by Seeder101** [comment] 2017-05-15 17:42
actually you're correct...the issue is with the breeze themes either with breeze dark or breeze the same issue no icons for qtransmission I don't know why! this issue is not a problem under different distros using the breeze suites

**Comment by demmm** [comment] 2017-05-15 18:04
Breeze theme does not have the transmission icon.
It may be that other distros you use, hardcode an icon during install/packaging.

**Comment by demmm** [comment] 2017-05-15 18:06
Best to open a request for breeze to add the transmission icons.

**Comment by demmm** [comment] 2017-05-16 15:20
Since it might never be implemented in Breeze, packaging has been adjusted to include some Plasma compatible icons, see commits:
https://github.com/KaOSx/apps/commit/19309d4e9447ac2af77e88a9feeaa916e355fcfc
https://github.com/KaOSx/apps/commit/5098d27c885eaf97156edb4a2a638e3ba2795b44

Closing this issue, report back if you still see icons issues.

**Closed by demmm** 2017-05-16 15:20 UTC
Labels: waiting for feedback
