### ISSUE TITLE
Firefox crashing

### ISSUE THREAD

**Issue by NoSavvy** [KaOSx/apps#232] opened 2024-11-01 16:10 UTC
#### Submission type

  - [x] Bug report
  - [ ] Feature Request

#### Package name & version you are having issues with or have a request for

> …

#### Used repositories

> …

#### Expected behaviour

> …

#### Actual behaviour

> …

#### Steps to reproduce the problem

> …

#### System info link created by Octopi > Tools > SysInfo

> …

**Comment by demmm** [comment] 2024-11-01 19:41
Duplicate of https://github.com/KaOSx/apps/issues/233

**Closed by demmm** 2024-11-01 19:41 UTC
