### ISSUE TITLE
Krita crashes on opening .DNG-files 

### ISSUE THREAD

**Issue by theyellowfish** [KaOSx/apps#53] opened 2016-04-13 20:27 UTC
Happens after updating to the current package 2.99.89-1.
If You choose opening a RAW-file Krita crashes instead op opening the import-dialogue.
It also occurs with files that Krita was able to open before getting updated.
The Issue reads "unknown type of file".
Does Anybody know how to fix the problem?

Thanks

Michael

**Comment by demmm** [comment] 2016-04-13 20:29
Is your system fully updated? Can you link a failing file?

**Comment by demmm** [comment] 2016-04-13 21:48
I found a .dng file that reproduced the issue.
A rebuild libraw fixed it here, please confirm.  Install new libraw with ```sudo pacman -U http://kaosx.tk/repo/build/libraw-0.17.1-2-x86_64.pkg.tar.xz```

**Comment by demmm** [comment] 2016-04-13 23:37
Looks like this commit is the change that broke Krita:
https://quickgit.kde.org/?p=krita.git&a=commitdiff&h=47f05f2d3730b630eceaf5ea0f551550a06e8283

KaOS will stay with 2.99.88 for now, but the very last part of this commit might need to be a revert patch for future builds.

**Comment by theyellowfish** [comment] 2016-04-14 19:20
@demmm 
The rebuild libraw fixes the problem, I'm quite amazed :-) 
I'm a Newbie to KaOS, after using Kubuntu for years. and I'm convinced this change was a right decision.

thanks for Your work

Michael

**Comment by demmm** [comment] 2016-04-14 20:12
Actually, the libraw rebuild was not the real/full fix, issue was upstream.
Fix was to still use 2.99.89, but partially revert the linked commit.
See line 23:
https://github.com/KaOSx/apps/commit/f17ddc54f53f9a52e5ee66fd48d22bb1ef00be42#diff-579f378fe52db37607f5b54a732750f2R23

this sed line re-adds all possible RAW files bck to Krita.

Issue will be closed once libraw and krita move from the [build] repo to the main/apps (stable) repos for all users.

**Comment by demmm** [comment] 2016-04-19 15:22
Libraw and Krita are now moved, closing

**Closed by demmm** 2016-04-19 15:22 UTC
Labels: bug, upstream
